air_health_data_platform:
  outputs:
    dev:
      type: athena
      s3_staging_dir: s3://project-2-air-health-data-platform/athena-results/
      catalog: AwsDataCatalog
      schema: air_health_gold
      region_name: eu-central-1
      work_group: project2-athena-wg
      threads: 4
      aws_profile_name: "{{ env_var('AWS_PROFILE', 'default') }}"
      aws_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
      aws_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
  target: dev
