name: Deploy Lambdas

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Lambda packages to S3
        run: |
          for file in $(find lambda_build -name "*.zip"); do
            key=$(echo "$file" | sed 's|lambda_build/||')
            aws s3 cp "$file" "s3://${{ secrets.S3_BUCKET }}/lambda_build/$key"
          done

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -input=false -auto-approve tfplan
